### ISSUE TITLE
Is Wasm compilation supported?

### ISSUE THREAD

**Issue by samuelburnham** [supranational/pasta-msm#1]
It looks like semolina only supports x86_64 and aarch64, but semolina usage is optional? I have had mixed results compiling pasta-msm/semolina to `wasm32-unknown-unknown`, and would like to clarify if it's a supported target. Thanks!

**Comment by dot-asm** [comment]
Yes, semolina is only supported on aarch64 and x86_64. Formally speaking semolina is a second-tier dependency. It merely "powers" sppark(*), which provides the actual interface to Nova. In other words, a more compelling question would be if sppark supports wasm.  Well, not that it does. I mean the answer would be the same for both:-(

(*) One can instantiate Pasta curves in sppark through blst_t.hpp, semolina merely takes advantage of the Pasta moduli' bit structure.

**Comment by samuelburnham** [comment]
Makes sense, thanks!
