### ISSUE TITLE
Compile error: failed to run custom build command for `sppark v0.1.5`

### ISSUE THREAD

**Issue by liqi16** [supranational/pasta-msm#12]
Hi! When I ran `cargo bench`, I met an error: `failed to run custom build command for sppark v0.1.5`. (Sorry, I am a beginner in Rust.) Does that mean my CUDA version is too low? How can I solve this problem if I don't have permission to upgrade CUDA? 

I am looking forward to hearing back from you. Thank you very much!

- Clone https://github.com/supranational/pasta-msm
- Run cargo bench

```
  Compiling pasta-msm v0.1.4 (/home/lq/project/pasta-msm)
error: failed to run custom build command for `sppark v0.1.5`

Caused by:
  process didn't exit successfully: `/home/lq/project/pasta-msm/target/release/build/sppark-e4c8a9a15b3da435/build-script-build` (exit status: 101)
  --- stdout
  cargo:ROOT=/home/lq/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sppark-0.1.5/sppark

  --- stderr
  thread 'main' panicked at /home/lq/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sppark-0.1.5/build.rs:67:13:
  Unsupported CUDA version 10.1 < 11.4
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by dot-asm** [comment]
> `Unsupported CUDA version 10.1 < 11.4`

The limitation was programmed based on user reports of test failures with 11.x prior 11.4. In case you wonder if 11.<4 failure necessarily means that your 10.1 doesn't work. The matter of fact is that we rely on APIs entries that were introduced in 11.0, so that 10.x was never a part of support matrix.
