### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by huitseeker** [supranational/pasta-msm#4]
https://github.com/supranational/pasta-msm/commit/76db1fb126e0d7e77a76720f11df5dbe5957c608 introduced a change to the `Cargo.toml` that allows using this crate with `pasta_curves` at version 0.5.0.

To benefit from this change, one could depend on the master branch of the present crate, but that would constitute a moving target, as any new commit could introduce an incompatibility. A new crate release would allow pinning the version of pasta-msm we depend on.

**Comment by huitseeker** [comment]
@dot-asm if there is a flavor of tooling that would help your job (e.g. a github action that publishes the crate upon receiving a tag, or maybe a config for [cargo-release](https://github.com/crate-ci/cargo-release)) I'm happy to set that up for you.

**Comment by dot-asm** [comment]
The reason for the delay is that there are sppark and semolina updates coming up shortly. Please allow some more time :-)

**Comment by dot-asm** [comment]
The new version is published. Even though sppark is not updated yet, this new version is future-proofed and tested against the unreleased version, so that whenever it's out, it would take a regular `cargo update` on the application side.
